version: "3.8"

services:

  postgres:
    image: postgres:16.0-bookworm
    container_name: ${POSTGRES_HOST}
    env_file:
      - .env
    ports:
      - "5454:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bet_net

  bet_maker_api:
    build:
      context: ../bet-maker
      dockerfile: api.dockerfile
      target: test_extended
    depends_on:
      - postgres
      - line_provider_api
    container_name: ${BET_API_HOSTNAME}
    env_file:                              # For production use secrets
      - .env
    environment:
      APP_MODE: Development
    ports:
      - "${BET_API_PORT}:${BET_API_PORT}"
    volumes:
      - ../bet-maker:/bet-maker            # Reference and fast reloading. Do not change COPY directive in dockerfile
    command: python3 main.py
    networks:
      - bet_net

  line_provider_api:
    build:
      context: ../line-provider
      dockerfile: Dockerfile
      args:
        API_PORT: ${LINE_API_PORT}
    container_name: ${LINE_API_HOSTNAME}
    env_file:
      - .env
    ports:                                 # In production use no "ports" directive, only "expose" with LINE_API_PORT
      - "${LINE_API_PORT}:${LINE_API_PORT}"
    volumes:
      - ../line-provider:/line-provider    # Reference and fast reloading. Do not change COPY directive in dockerfile
    networks:
      - bet_net

networks:
  bet_net:
    driver: bridge

volumes:
  postgres_data: